### ISSUE TITLE
översättningarna syns inte

### ISSUE THREAD

**Issue by Mehetweret** [uppfinnarn/korform#2]
Tack för meddelandet att översättningarna är merged, men de syns inte och jag hittar ingenstans som jag kan byta språk. Det borde i så fall finnas på Sites, tänker jag, men där finns inget språkval. Så allt är fortfarande på engelska.

**Comment by liclac** [comment]
Det är baserat på vad användarens webbläsare är inställd på, om den är på svenska så är sidan det också
